"""data update

Revision ID: 061cecdb68a9
Revises: 6e7fc1de3038
Create Date: 2023-11-02 15:49:19.423684

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '061cecdb68a9'
down_revision = '6e7fc1de3038'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('acquisitions', 'source_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_company_country_code'), 'company', ['country_code'], unique=False)
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=False)
    op.alter_column('ipos', 'valuation_amount',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ipos', 'valuation_amount',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_index(op.f('ix_company_country_code'), table_name='company')
    op.alter_column('acquisitions', 'source_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
