"""data

Revision ID: 6e7fc1de3038
Revises: 
Create Date: 2023-11-01 10:57:46.980509

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6e7fc1de3038'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('homepage_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('overview', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acquisitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acquisition_id', sa.Integer(), nullable=False),
    sa.Column('price_amount', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price_currency_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('acquired_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('acquiring_object_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('acquired_object_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['acquired_object_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['acquiring_object_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipo_id', sa.Integer(), nullable=False),
    sa.Column('valuation_amount', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('valuation_currency_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raised_amount', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raised_currency_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('public_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stock_symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('object_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ipos')
    op.drop_table('acquisitions')
    op.drop_table('company')
    # ### end Alembic commands ###
